spring:
  datasource:
    url: jdbc:mysql://localhost:3306/younet
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  # redis 설정 - 01/21
  data:
    redis:
      host: localhost
      port: 6379

  # 인증 메일 전송 - 01/21 - 01/23 최종 수정
  mail:
    host: smtp.gmail.com
    port: 587
    username: umcyounet@gmail.com
    password: lkzxupetjvvekswu
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3b73fcf4ca8748158d21ac1aea0cda46
            client-secret: yU1ydnfNqQNEjYLlRMT1gliSmm67opKB
            redirect-uri: https://localhost:8080/oauth2/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  header: Authorization
  secret: younetspringbootsecretkeysdlfksjdflwlekfjsldkjflskejflskejfaoeiubnscom
  token-validity-in-seconds: 86400
cloud:
  aws:
    s3:
      bucket: younet-server
      path:
        post: posts
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY_ID}