name: YOUNET_SERVER

on:
  push:
    branches: [ main ] 

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
      - name: ssh to ec2
        uses: appleboy/ssh-action@master y
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}   
          host: ${{ secrets.HOST }}   
          username: ${{ secrets.USER }}  
          script: | #실행할 코드
            cd /home/ubuntu
            sh deploy.sh    #배포 스크립트 파일 실행
            
            nohup java -jar younet-0.0.1-SNAPSHOT.jar > nohup.out 2> nohup.err < /dev/null &   
           
